server:
  port: 0

spring:
  application:
    name: record
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/record
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

clients:
  nutritionIntake:
    name: nutritionIntake
    retrieve-data:
      url: /api/nutritionIntake/{recordId}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_URL:localhost}:9411/api/v2/spans
