version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_MANAGEMENT_HTTP_AUTH: "none"
    volumes:
      - rabbitMQ-data:/var/lib/rabbitmq
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql-db-record:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: record
    volumes:
      - recordVolume:/var/lib/mysql
  mysql-db-nutriton:
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nutritionIntake
    volumes:
      - nutritionVolume:/var/lib/mysql
  mysql-db-user:
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - userVolume:/var/lib/mysql
volumes:
  recordVolume:
  nutritionVolume:
  userVolume:
  rabbitMQ-data:

