# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: discovery-service-CICD-pipeline

on:
  push:
    paths:
      - 'microServices/discover-service' 

jobs:
  discovery-service-ci:
    runs-on: windows-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        cache: 'maven'
        distribution: corretto

    - name : Test && Build
      working-directory: ./microServices/discover-service
      run: |
        mvn test
        mvn build

    - name: Set the build project in artefact
      uses: actions/upload-artifact@v3
      with:
        name: buildProject
        path: microServices/discover-service/target/discover-service-1.0-SNAPSHOT.jar
        if-no-files-found: error

  discovery-service-cd:
      needs: discovery-service-ci
      runs-on: windows-latest  
      steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Download the build project 
        uses: actions/download-artifact@v3
        with:
          name: buildProject
          path: microServices/discover-service/target
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/discovery-service-tracker-app -f microServices/discover-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/discovery-service-tracker-app
