name: server-reactiveVersion-CICD-pipeline

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Run the workflow'
        required: true
  push:
    paths:
      - 'reactive version/monolithic approach/**' 

jobs:
  server-reactiveVersion-cicd:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        cache: 'maven'
        distribution: corretto

    - name : Test && Build && Deploy
      working-directory: ./reactive version/monolithic approach
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy
