name: server-reactiveVersion-CICD-pipeline

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Run the workflow'
        required: true
  push:
    paths:
      - 'reactive version/monolithic approach/**' 

jobs:
  server-reactiveVersion-cicd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Docker Image
      working-directory: ./reactive version/monolithic approach
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy
