name: server-reactiveVersion-CICD-pipeline

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Run the workflow'
        required: true
  push:
    paths:
      - 'reactive version/monolithic approach/**' 

jobs:
  server-reactiveVersion-cicd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Docker Image
      working-directory: ./reactive version/monolithic approach
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy \
        --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
        --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
        --build-arg DB_HOST=${{ secrets.DB_HOST }} \
        --build-arg ORIGINS=${{ secrets.ORIGINS }} \
        --build-arg FRONT_END_URL=${{ secrets.FRONT_END_URL }} \
        --build-arg SENDINBLUE_API_KEY=${{ secrets.SENDINBLUE_API_KEY }} \
        --build-arg EMAIL_SENDER=${{ secrets.EMAIL_SENDER }} \
        --build-arg FOOD_DATA_API_KEY=${{ secrets.FOOD_DATA_API_KEY }} \
        --build-arg FOOD_DATA_API_ID=${{ secrets.FOOD_DATA_API_ID }} \
        --build-arg FOOD_DATA_API_URL=${{ secrets.FOOD_DATA_API_URL }} \
        --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
        .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutri-guide-buddy