version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitMQ-data:/var/lib/rabbitmq
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql-db-record:
    container_name: mysql-db-record
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: record
    volumes:
      - recordVolume:/var/lib/mysql
  mysql-db-nutriton:
    container_name: mysql-db-nutriton
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nutritionIntake
    volumes:
      - nutritionVolume:/var/lib/mysql
  mysql-db-user:
    container_name: mysql-db-user
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - userVolume:/var/lib/mysql
  discovery-service:
    build:
      context: ../discover-service/.
    container_name: discovery-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
  gateway-service:
    build:
      context: ../gateway-service/.
    container_name: gateway-service
    environment:
      ZIPKIN_URL: zipkin
      EUREKA_HOST: discovery-service
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - discovery-service
  auth-service:
    build:
      context: ../auth-service/.
    container_name: auth-service
    environment:
      DB_HOST: mysql-db-user
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
  vitamin-service:
    build:
      context: ../vitamin/.
    container_name: vitamin-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  electrolyte-service:
    build:
      context: ../electrolyte/.
    container_name: electrolyte-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  macronutrient-service:
    build:
      context: ../macronutrient/.
    container_name: macronutrient-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin

    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  record-service:
    build:
      context: ../record/.
    container_name: record-service
    environment:
      DB_HOST: mysql-db-record
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
      - rabbitmq
  nutrition-intake-service:
    build:
      context: ../nutritionIntake/.
    container_name: nutrition-intake-service
    environment:
      DB_HOST: mysql-db-nutriton
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
      - rabbitmq
      - record-service
      - macronutrient-service
      - vitamin-service
      - electrolyte-service
volumes:
  recordVolume:
  nutritionVolume:
  userVolume:
  rabbitMQ-data:

