version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./kafka/zookeeper/zookeeper-data:/var/lib/zookeeper/data
      - ./kafka/zookeeper/zookeeper-log:/var/lib/zookeeper/log
      - ./kafka/zookeeper/zookeeper-secrets:/etc/zookeeper/secrets
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka/broker/kafka-secrets:/etc/kafka/secrets
      - ./kafka/broker/kafka-data:/var/lib/kafka/data
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql-db-record:
    container_name: mysql-db-record
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: record
    volumes:
      - record-data:/var/lib/mysql
  mysql-db-user:
    container_name: mysql-db-user
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - user-data:/var/lib/mysql
  mysql-db-storage:
    container_name: mysql-db-storage
    restart: always
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - storage-data:/var/lib/mysql
  discovery-server:
    image: svetlindimitrov/discovery-server-tracker-app
    container_name: discovery-server
    environment:
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
  gateway-server:
    image: svetlindimitrov/gateway-server-tracker-app
    container_name: gateway-server
    environment:
      ZIPKIN_URL: zipkin
      EUREKA_HOST: discovery-server
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - discovery-server
  auth-server:
    image: svetlindimitrov/auth-server-tracker-app
    container_name: auth-server
    restart: always
    environment:
      KAFKA_HOST: broker:29092
      DB_HOST: mysql-db-user
      DB_PORT: 3306
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-server
      - discovery-server
      - broker
  vitamin-server:
    image: svetlindimitrov/vitamin-server-tracker-app
    container_name: vitamin-server
    environment:
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-server
      - gateway-server
  electrolyte-server:
    image: svetlindimitrov/electrolyte-server-tracker-app
    container_name: electrolyte-server
    environment:
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-server
      - gateway-server
  macronutrient-server:
    image: svetlindimitrov/macronutrient-server-tracker-app
    container_name: macronutrient-server
    environment:
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-server
      - gateway-server
  food-server:
    image: svetlindimitrov/food-server-tracker-app
    container_name: food-server
    environment:
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-server
      - gateway-server
  record-server:
    restart: always
    image: svetlindimitrov/record-server-tracker-app
    container_name: record-server
    environment:
      DB_HOST: mysql-db-record
      DB_PORT: 3306
      EUREKA_HOST: discovery-server
      ZIPKIN_URL: zipkin
      KAFKA_HOST: broker:29092
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-server
      - discovery-server
      - broker
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-data:/prometheus
    depends_on:
      - record-server
  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
volumes:
  user-data:
  storage-data:
  record-data: