version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_MANAGEMENT_HTTP_AUTH: "none"
    volumes:
      - rabbitMQ-data:/var/lib/rabbitmq
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql-db-record:
    container_name: mysql-db-record
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: record
    volumes:
      - recordVolume:/var/lib/mysql
  mysql-db-nutriton:
    container_name: mysql-db-nutriton
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nutritionIntake
    volumes:
      - nutritionVolume:/var/lib/mysql
  mysql-db-user:
    container_name: mysql-db-user
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - userVolume:/var/lib/mysql
  discovery-service:
    build:
      context: ../discover-service/.
    container_name: discovery-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
volumes:
  recordVolume:
  nutritionVolume:
  userVolume:
  rabbitMQ-data:

