version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
      - zookeeper-secrets:/etc/zookeeper/secrets
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-secrets:/etc/kafka/secrets
      - kafka-data:/var/lib/kafka/data
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql-db-record:
    container_name: mysql-db-record
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: record
    volumes:
      - recordVolume:/var/lib/mysql
  mysql-db-nutriton:
    container_name: mysql-db-nutriton
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nutritionIntake
    volumes:
      - nutritionVolume:/var/lib/mysql
  mysql-db-user:
    container_name: mysql-db-user
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    volumes:
      - userVolume:/var/lib/mysql
  discovery-service:
    build:
      context: ../discover-service/.
    container_name: discovery-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
  gateway-service:
    build:
      context: ../gateway-service/.
    container_name: gateway-service
    environment:
      ZIPKIN_URL: zipkin
      EUREKA_HOST: discovery-service
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - discovery-service
  auth-service:
    build:
      context: ../auth-service/.
    container_name: auth-service
    environment:
      DB_HOST: mysql-db-user
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
  vitamin-service:
    build:
      context: ../vitamin/.
    container_name: vitamin-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  electrolyte-service:
    build:
      context: ../electrolyte/.
    container_name: electrolyte-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  macronutrient-service:
    build:
      context: ../macronutrient/.
    container_name: macronutrient-service
    environment:
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin

    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
  record-service:
    build:
      context: ../record/.
    container_name: record-service
    environment:
      DB_HOST: mysql-db-record
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
      KAFKA_HOST: broker:29092
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
      - broker
  nutrition-intake-service:
    build:
      context: ../nutritionIntake/.
    container_name: nutrition-intake-service
    environment:
      DB_HOST: mysql-db-nutriton
      DB_PORT: 3306
      EUREKA_HOST: discovery-service
      ZIPKIN_URL: zipkin
      KAFKA_HOST: broker:29092
    depends_on:
      - zipkin
      - mysql-db-user
      - gateway-service
      - discovery-service
      - broker
      - record-service
      - macronutrient-service
      - vitamin-service
      - electrolyte-service
volumes:
  recordVolume:
  nutritionVolume:
  userVolume:
  rabbitMQ-data:
  kafka-secrets:
  kafka-data:
  zookeeper-secrets:
  zookeeper-data:
  zookeeper-log:

