global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'gateway-metrics'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['docker.host.internal:8080']
